In [15]:
import numpy as np

In [16]:
def step_function_i(x):
    if x > 0:
        a = 1
    else:
        a = 0
    return a

step_function_i(-1)

0

In [17]:
def step_function_ii(x):
    y = x > 0
    return y.astype(int)

In [18]:
x = np.array([-1.0, 1.0, 2.0])
step_function_ii(x)

array([0, 1, 1])

In [19]:
x = np.array([-1.0, 1.0, 2.0])
x

array([-1.,  1.,  2.])

Rと同じように、bool型の配列を作ることができる

```py
x = np.array([1, 2, 3])

# 配列`x`のうち、2以上のものをTrue、それ以外をFalseとし、その配列をyに代入する
y = x >= 2
```

In [20]:
y = x > 0
y

array([False,  True,  True])