In [1]:
# 多次元配列
import numpy as np

A = np.array([1, 2, 3, 4])
print(A)

[1 2 3 4]


In [ ]:
# Aの次元
np.ndim(A)

1

In [ ]:
# Aの配列の形状
np.shape(A)

(4,)

In [4]:
B = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [10, 11, 12]
    ]
)

print(B)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
np.shape(B)
# (4, 3)と出力される
# 「4行3列の行列」という意味

(4, 3)