次の式を実装する。この式は、入力層（0層目）から隠れ層（1層目）へのフォワード処理を意味する。つまり重みを付ける最初の層への入力なので右肩に「(1)」を付けている。
$${
  \bm{A}^{(1)} = \bm{X}\bm{W}^{(1)} + \bm{B}^{(1)}
}$$
すなわち、
$${
  \begin{pmatrix}
    a_1^{(1)} & a_2^{(1)} & a_3^{(1)}
  \end{pmatrix}
  =
  \begin{pmatrix}
    x_1 & x_2
  \end{pmatrix}
  \begin{pmatrix}
    w_{11}^{(1)} & w_{21}^{(1)} & w_{31}^{(1)} \\
    w_{12}^{(1)} & w_{22}^{(1)} & w_{32}^{(1)}
  \end{pmatrix}
  +
  \begin{pmatrix}
    b_1^{(1)} b_2^{(1)} b_3^{(1)}
  \end{pmatrix}
}$$

ここで気づいたと思いますが、普段の行列の要素の添え字の列番号と行番号が逆になっている。そのため、線形代数学に馴染みのある方は次のように考えれば明快になるだろう。
$${
  \begin{pmatrix}
    a_1^{(1)} \\
    a_2^{(1)} \\
    a_3^{(1)}
  \end{pmatrix}^T
  =
  \begin{pmatrix}
    x_1 \\
    x_2
  \end{pmatrix}^T
  \begin{pmatrix}
    w_{11}^{(1)} & w_{12}^{(1)} \\
    w_{21}^{(1)} & w_{22}^{(1)} \\
    w_{31}^{(1)} & w_{32}^{(1)}
  \end{pmatrix}^T
  +
  \begin{pmatrix}
    b_1^{(1)} \\
    b_2^{(1)} \\
    b_3^{(1)}
  \end{pmatrix}^T
}$$
すなわち、
$${
  \begin{pmatrix}
    a_1^{(1)} \\
    a_2^{(1)} \\
    a_3^{(1)}
  \end{pmatrix}
  =
  \begin{pmatrix}
    w_{11}^{(1)} & w_{12}^{(1)} \\
    w_{21}^{(1)} & w_{22}^{(1)} \\
    w_{31}^{(1)} & w_{32}^{(1)}
  \end{pmatrix}
  \begin{pmatrix}
    x_1 \\
    x_2
  \end{pmatrix}
  +
  \begin{pmatrix}
    b_1^{(1)} \\
    b_2^{(1)} \\
    b_3^{(1)}
  \end{pmatrix}
}$$

数学に馴染みのある私にとっては、各行列の転置をとり、 ${A = B \iff A^T = B^T}$ という性質を用いて変形した後の形式で表示したほうが添え字と行番号・列番号の整合性が取れやすいので、今後この本「ゼロから作る Deep Learning」を読み進めていくときは、必要に応じて「転置をとればいいのだな」と思えば大丈夫だろう。

In [1]:
import numpy as np

X = np.array([1.0, 0.5])
W1 = np.array([
    [0.1, 0.3, 0.5],
    [0.2, 0.4, 0.6]
])
B1 = np.array([0.1, 0.2, 0.3])

print(W1.shape)
print(X.shape)
print(B1.shape)

A1 = np.dot(X, W1) + B1
print(A1)

(2, 3)
(2,)
(3,)
[0.3 0.7 1.1]


続いて、生成された重み付きの和を出力するための活性化関数に写す操作を実装する。

ここではシグモイド関数を活性化関数として選択する。
$${
  h(x)
  =
  \mathrm{Sig}(x)
  =
  \frac{1}{1 + e^{-x}}
}$$

In [3]:
import numpy as np

X = np.array([1.0, 0.5])
W1 = np.array([
    [0.1, 0.3, 0.5],
    [0.2, 0.4, 0.6]
])
B1 = np.array([0.1, 0.2, 0.3])

print(W1.shape)
print(X.shape)
print(B1.shape)

A1 = np.dot(X, W1) + B1
# print(A1)

def sigmoid(x):
    sig = 1 / (1 + np.exp(-x))
    return sig

Z1 = sigmoid(A1)

print(A1)
print(Z1)

(2, 3)
(2,)
(3,)
[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]


続いて、1層目から2層目までの実装を行う。

In [8]:
import numpy as np

X = np.array([1.0, 0.5])
W1 = np.array([
    [0.1, 0.3, 0.5],
    [0.2, 0.4, 0.6]
])
B1 = np.array([0.1, 0.2, 0.3])

# print(W1.shape)
# print(X.shape)
# print(B1.shape)

A1 = np.dot(X, W1) + B1
# print(A1)

def sigmoid(x):
    sig = 1 / (1 + np.exp(-x))
    return sig

Z1 = sigmoid(A1)

# print(A1)
# print(Z1)

W2 = np.array([
    [0.1, 0.4],
    [0.2, 0.5],
    [0.3, 0.6]
])

B2 = np.array([0.1, 0.2])

print(Z1.shape)
print(W2.shape)
print(B2.shape)

A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)

print(A2)
print(Z2)

(3,)
(3, 2)
(2,)
[0.51615984 1.21402696]
[0.62624937 0.7710107 ]


最後に、第2層目から出力層への信号の伝達を実装する。

In [9]:
import numpy as np

X = np.array([1.0, 0.5])
W1 = np.array([
    [0.1, 0.3, 0.5],
    [0.2, 0.4, 0.6]
])
B1 = np.array([0.1, 0.2, 0.3])

# print(W1.shape)
# print(X.shape)
# print(B1.shape)

A1 = np.dot(X, W1) + B1
# print(A1)

def sigmoid(x):
    sig = 1 / (1 + np.exp(-x))
    return sig

Z1 = sigmoid(A1)

# print(A1)
# print(Z1)

W2 = np.array([
    [0.1, 0.4],
    [0.2, 0.5],
    [0.3, 0.6]
])

B2 = np.array([0.1, 0.2])

# print(Z1.shape)
# print(W2.shape)
# print(B2.shape)

A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)

# print(A2)
# print(Z2)

def identity_function(x):##定義しなくてもよいのでは？という声はいったん抑えよ。
    return x

W3 = np.array([
    [0.1, 0.3],
    [0.2, 0.4]
])
B3 = np.array([0.1, 0.2])

A3 = np.dot(Z2, W3) + B3
Y = identity_function(A3)   # 大廻な方法だが、簡単のため

print(Y)

[0.31682708 0.69627909]
