# 勾配

In [2]:
import numpy as np

# 関数の定義
def function_2(x):
    return x[0]**2 + x[1]**2
    # return np.sum(x**2)でもOK

# 勾配を実装する
def numerical_gradient(f, x):
    h = 1e-4    # 0.0001
    grad = np.zeros_like(x) # xと同じ形状の配列を生成

    for idx in range(x.size):
        tmp_val = x[idx]
        # f(x + h)の計算
        x[idx] = tmp_val + h
        fxh1 = f(x)

        # f(x - h)の計算
        x[idx] = tmp_val - h
        fxh2 = f(x)

        grad[idx] = (fxh1 - fxh2) / (2*h)
        x[idx] = tmp_val    # 値をもとに戻す
    
    return grad

In [3]:
numerical_gradient(function_2, np.array([3.0, 4.0]))

array([6., 8.])

In [4]:
numerical_gradient(function_2, np.array([0.0, 2.0]))

array([0., 4.])

In [5]:
numerical_gradient(function_2, np.array([3.0, 0.0]))

array([6., 0.])