In [ ]:
# 行列積
import numpy as np

A = np.array(
    [
        [1, 2],
        [3, 4]
    ]
)

# np.shape(A)でも出力可能
A.shape

(2, 2)

In [4]:
B = np.array([
    [5, 6],
    [7, 8]
])

B.shape

(2, 2)

In [5]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [11]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(A.shape)

B = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(B.shape)

np.dot(A, B)

(2, 3)
(3, 2)


array([[22, 28],
       [49, 64]])

In [7]:
C = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

try:
    np.dot(A, C)
except ValueError:
    print("やはり、2*2行列と3*2行列の行列積は計算できなかったか。")

やはり、2*2行列と3*2行列の行列積は計算できなかったか。


In [16]:
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

B = np.array([
    [7],
    [8]
])

print(f"{A}\n は{A.shape}で、\n {B}は{B.shape}である。\n")

print(f"行列\n {A}\n と行列\n {B}\n の行列積は\n {np.dot(A, B)}\n となる。")

[[1 2]
 [3 4]
 [5 6]]
 は(3, 2)で、
 [[7]
 [8]]は(2, 1)である。

行列
 [[1 2]
 [3 4]
 [5 6]]
 と行列
 [[7]
 [8]]
 の行列積は
 [[23]
 [53]
 [83]]
 となる。


In [21]:
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

B = np.array([
    [7],
    [8]
])

C = np.array([1, 2, 3])
D = np.array([1, 2])

np.dot(C, A)    # 0×3行列(配列)と3×2行列の行列積は、0×2行列(配列)となる。
np.dot(A, D)    # 3×2行列と2×0行列(配列)の行列積は、3×0行列(配列)となる。

array([ 5, 11, 17])