# ソフトマックス関数を扱う際の注意点

ソフトマックス関数は指数関数を用いている点から、容易に巨大数になる可能性がある。コンピュータでは有効桁数に限りがあるので、それを超過する場合（オーバーフローする場合）は、少し工夫が必要。

そのとき、次の関係式が成り立つことを用いて、その欠点を回避することが一般的である。

$${
  \frac{\exp(a_k)}{\sum_{i = 1}^{n}\exp(a_i)}
  =
  \frac{\exp(a_k + C)}{\sum_{i = 1}^{n}\exp(a_i + C)},\ C\in\mathbb{R}
}$$

In [11]:
import numpy as np
np.seterr(all = "raise")

a = np.array([1010, 1000, 990])

try:
    np.exp(a) / np.sum(np.exp(a))
except FloatingPointError:
    print("RuntimeWarningという警告を吐いてしまい、出力される要素がすべて`nan`（not a number; 不定）になってしまう。")

RuntimeWarningという警告を吐いてしまい、出力される要素がすべて`nan`（not a number; 不定）になってしまう。


In [7]:
np.seterr(all = "warn")
a = np.array([1010, 1000, 990])
np.exp(a) / np.sum(np.exp(a))

C:\Users\Cyril\AppData\Local\Temp\ipykernel_13796\2685156142.py:3: RuntimeWarning: overflow encountered in exp
  np.exp(a) / np.sum(np.exp(a))
C:\Users\Cyril\AppData\Local\Temp\ipykernel_13796\2685156142.py:3: RuntimeWarning: invalid value encountered in divide
  np.exp(a) / np.sum(np.exp(a))


array([nan, nan, nan])

In [8]:
c = np.max(a)

a - c

array([  0, -10, -20])

In [9]:
np.exp(a - c) / np.sum(np.exp(a - c))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

オーバーフローの対策を講じた最新版のソフトマックス関数を以下に記す。

In [10]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)   # オーバーフロー対策
    sum_exp_a = np.sum(exp_a)

    y = exp_a / sum_exp_a
    return y

a = np.array([1010, 1000, 990])
softmax(a)

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])